### ISSUE TITLE
Remove trailing spaces after a comment symbol

### ISSUE THREAD

**Issue by barraponto** [scrooloose/nerdcommenter#102]
I usually comment stuff with a space between the comment symbol and the actual comment. Like this:

    # commented code

But using `<leader>cu` leaves the space in, resulting in badly indented lines in python. Is there a workaround for this?

**Comment by jonafato** [comment]
As of the merging of #183, this should be fixed.

**Comment by mightyiam** [comment]
Thank you, @jonafato

**Comment by alerque** [comment]
For python this is currently the default behavior. For other languages you can set `let g:NERDSpaceDelims = 1` for the extra space to be your default.
