### ISSUE TITLE
[error, please cancel] LaTeX support?

### ISSUE THREAD

**Issue by fradeve** [scrooloose/nerdcommenter#105]
I'm trying to get NERDCommenter to work with LaTeX files (.tex), but even if `:set ft?` shows me `filetype=tex`, NERDCommenter does not work. Enquiring over, I see that the `.tex` filetype is not hardcoded among the others in `plugin/NERD_commenter.vim` (we have ConTeX, LyTeX, TeXinfo).

Now, I can add this by myself, but probably introducing LaTeX support could be a good idea.

**Comment by icymist** [comment]
Me too!
