### ISSUE TITLE
gvim plugin menu heading is not descriptive

### ISSUE THREAD

**Issue by robEllenberg** [scrooloose/nerdcommenter#112]
It's a very minor issue, but I just started using gvim today, and noticed that the plugin menu isn't very descriptive:
![NERDcommenter-menu](https://f.cloud.github.com/assets/1210940/383067/8d52c192-a60a-11e2-90e6-f469b42a2db4.png)

Otherwise, thanks for a great plugin!

**Comment by alerque** [comment]
There isn't a ton of room for long descriptions, but if you can think of better wording for any of those menu items they are an easy fix in the source (see [line 2857ff in plugin/NERD_commenter.vim](https://github.com/scrooloose/nerdcommenter/blob/master/plugin/NERD_commenter.vim#L2857)). The wording mostly looks good to me but I would be happy to consider a pull request for any that could be improved, so hit edit and do your best. Just keep in mind that these are menu items, not full explanations of how to use the features (which is what [the docs](https://github.com/scrooloose/nerdcommenter/blob/master/doc/NERD_commenter.txt) are for (as seen in `:help nerdcommenter`).
