### ISSUE TITLE
change the sexy format

### ISSUE THREAD

**Issue by nbari** [scrooloose/nerdcommenter#125]
Any idea of how to extend/change the format of the sexy:

```
/*
 *
 */
```

To something like

```
/**
 *
 */
```

Basically I can to star the command with /** and not just a single /*

any ideas?

regards.

**Comment by alerque** [comment]
Yes. You can get this by adding a pair of custom delimiters for your language:

```
let g:NERDSpaceDelims = 1
let g:NERDCustomDelimiters = { 'c': { 'left': '/**','right': '*/' } }
```

**Comment by fantiq** [comment]
there is my .vimrc , it doesn't work

```
Plugin 'scrooloose/nerdcommenter'
let g:NERDSpaceDelims=1
let g:NERDCustomDelimiters={ 'php' : { 'left': '/**','right': '*/'} }
```

when i use `n<leader>cs` the comment is started with `/*`   rather then `/**`

**Comment by alerque** [comment]
@fantiq It does work, but that isn't your full rc file so I can't be sure what's going on. I suspect  you might be setting or detecting the file type _after_ NerdCommenter has already initialized. In any event if you can't get it to work and think there is a problem please post a new issue. Thanks.

**Comment by fantiq** [comment]
@alerque thanks for your response very much! yes , it is work very will when i reopen the vim .
but there is a new question and i have post a new issue here [issue:288](https://github.com/scrooloose/nerdcommenter/issues/288)
