### ISSUE TITLE
Feature Request - Pick Default for `NERDComToggleComment`

### ISSUE THREAD

**Issue by amadeus** [scrooloose/nerdcommenter#128]
I prefer to use `NERDComAlignedComment` but having to use 2 different key combos to turn comments on an off is a bit annoying.

It would be great if I could specify what type of commenting to use for `NERDComToggleComment`.

I this feasible?

**Comment by fespinoza** [comment]
I would like the same thing

**Comment by benwoodward** [comment]
I too would like this

**Comment by solacortez** [comment]
Fuk

**Comment by alerque** [comment]
Does `let g:NERDDefaultAlign = 'left'` not take care of this?

**Comment by alerque** [comment]
I'm pretty sure that as of #24 being merged this is taken care of. If I'm missing something feel free to comment  back and I'll re-open.
