### ISSUE TITLE
NERD commenter commands are not available as Ex commands.

### ISSUE THREAD

**Issue by qazwsxpawel** [scrooloose/nerdcommenter#135]
Being a Vim newb I do not imply that they should have been. The problem that brought me here is as follows: I would like to remap `NERDComInvertComment` functionality to say `<C-/>` but I do not know how to do this since there is no Ex command I can assign it to, as far as I know.

**Comment by turboMaCk** [comment]
:+1:

**Comment by alerque** [comment]
Check out the end of the plugin source file for all the mappings that are created and the modes they run in. You can call the functions directly from ex mode like this:

```
:call NERDComment('n', "Invert")
```

You can use this way of calling functions to setup your own maps if you like.
