### ISSUE TITLE
asm comments

### ISSUE THREAD

**Issue by nickdesaulniers** [scrooloose/nerdcommenter#147]
ugh this was rough for me to figure out.  In my asm file, using nerdcommenter prepends a semicolon when a pound sign is needed.  I'll try and find the link but I may have seen that the comment is ISA specific, which sounds weird to me but I could have sworn...

**Comment by alerque** [comment]
The pound sign is the alternate syntax for this language. You can switch the primary/alternate delimiters using `<leader>ca`, then the default comment action will use pound signs.
