### ISSUE TITLE
Comments do not start in the first column

### ISSUE THREAD

**Issue by firedev** [scrooloose/nerdcommenter#162]
When commenting indented code here is what I would expect:
```ruby
# def
#   whatever
# end
```
I am getting this instead:
```ruby
#def
  #whatever
#end
```

Is there a way to configure `nerdcommenter` to start comments at the first column and have a single space after the comment sign?

**Comment by CleanCut** [comment]
I prefer to have them all in the first column as well!

+1

**Comment by albertnetymk** [comment]
I would like to have this feature as well, for auto formatter would still keep the original indentation in the first case.

**Comment by jargot** [comment]
This is an already implemented feature, just use NERDComAlignedComment:
[count]<leader>cl
or 
[count]<leader>cb

**Comment by cespare** [comment]
It would still be nice to have a way to toggle comments using aligned mode.

**Comment by alerque** [comment]
As of my merge of #24, there is now a way to toggle the default (check the help and review the `NERDDefaultAlign` config option). I hope that helps everyone. If there is anything further this is missing let me know.

**Comment by cespare** [comment]
Excellent! Thanks @alerque!

**Comment by albertnetymk** [comment]
`let g:NERDDefaultAlign = 'left'` works as expected. Thank you @alerque.
