### ISSUE TITLE
How to use it? Can any one at least explain the meaning of each part of this command in README?

### ISSUE THREAD

**Issue by legatoo** [scrooloose/nerdcommenter#165]
`[count]<leader>cc |NERDComComment|`
what's the meaning of each part? WHat should I input? I enter visual mode and select 5 lines, and what should I put? I tried `cc`, `\cc`, `/cc`, `/cc |NERDComCommenter|`. Just get crazy, I begin to vim, and seems docs are not friendly. maybe tell people what should input or explain each part of command is better.

**Comment by alerque** [comment]
The README is a very abbreviated help, for full documentation see the vim help system:

    :help nerdcommenter

You do need to know what your leader is. Often it is `\` but some locales use `,` or other variants. Whatever that key is is what you use when it says `<leader>` in the docs. One you select text, hitting `<leader>cc` should comment out the selection.
