### ISSUE TITLE
Python: Append comment: missing extra space before #

### ISSUE THREAD

**Issue by thomasgubler** [scrooloose/nerdcommenter#166]
When writing python code `<leader>cA` only adds one space after the code:
`<some code> # <comment starts here>`

However, according to [PEP 8](http://legacy.python.org/dev/peps/pep-0008/#inline-comments)  at least 2 spaces are required
`<some code>  # <comment starts here>`

Please note that this is not the same as #104 which can be solved by `let g:NERDSpaceDelims = 1`

**Comment by alerque** [comment]
See also #240. Something is wonky here. Are you sure you're still not getting a space before the delimiter? A lot has changed in the code since this report and I'd like to hear an update on whether it is working as expected or not. Thanks!

**Comment by Aluriak** [comment]
I can't reproduce the OP behavior.
`<leader>cA` correctly appends two ' ', one '#' and one ' ' at the end of the line.

As expected, `let g:NERDSpaceDelims = 1` is mandatory in order to get the last space.

**Comment by zgpio** [comment]
Is this problem solved?
