### ISSUE TITLE
opening folders/files not working under zsh

### ISSUE THREAD

**Issue by comatory** [scrooloose/nerdcommenter#169]
I am having problems with this plugin while using zsh shell. Instead of arrows that are on the left side (indication of folders), I get question marks. Enter/`o` does not work so it's impossible to open folders and files.

**Comment by alerque** [comment]
Are you sure this issue report is on the right repository? This is for a vim script that adds comment syntax to files being edited. It sounds like you may have an issue with some other program. If I'm wrong, please explain in more detail.
