### ISSUE TITLE
Comment lines lile "/* x */" results in /*[> x <] */, thus uncomment it result in [> x <].

### ISSUE THREAD

**Issue by pengubco** [scrooloose/nerdcommenter#170]
I have a habit of commenting a single line using /* */. For example, using [leader]cm.
When I need to comment these comment-lines out (for debugging) and then getting these comment-lines back after. I got a bunch of [> my comment lines <].

For example, 
```
 int n = 3;                                         
  /*call function asynchronously:*/
 std::future<bool> fut = std::async (is_prime,n);
 std::cout<< n << std::endl;
```

Run [leader]cm in visual select mode results in ,
```
 /*int n = 3;                                           
  [>call function asynchronously:<]
 std::future<bool> fut = std::async (is_prime,n);*/
```

**Comment by martinwk** [comment]
Same here. It did work in an older version I used (don't know which)

**Comment by knight42** [comment]
My [PR](https://github.com/scrooloose/nerdcommenter/pull/226) has fixed this issue.

**Comment by alerque** [comment]
Thanks for reviewing your PR @knight42, but I'm not sure this is actually fixed. I tested the example @pengubco let off with and I get a different result, but still broken. The nested comment placeholders aren't getting placed, but this causes the comment nesting to break. The real fix would be to set the placeholders, but also _unset_ them appropriately. Would your patch actually do this correctly? Or does in actually work now and I'm missing something?

**Comment by knight42** [comment]
@alerque  The problem we encountered before is that if the following lines are uncommented,
```
 /*int n = 3;                                           
  [>call function asynchronously:<]
 std::future<bool> fut = std::async (is_prime,n);*/
```
we' ll get
```
 int n = 3;                                           
  [>call function asynchronously:<]
 std::future<bool> fut = std::async (is_prime,n);
```
But using the latest `nerdcommenter`, we' ll get
```
 int n = 3;                                           
  /*call function asynchronously:*/
 std::future<bool> fut = std::async (is_prime,n);
```

Could I know the different result in your test?

**Comment by alerque** [comment]
@knight42 I get the same result for that particular case of _uncommenting_. The issue I see is with commenting it in the first place. For reference given this file with `filetype=c`:

```c
int n = 3;                                         
/*call function asynchronously:*/
std::future<bool> fut = std::async (is_prime,n);
std::cout<< n << std::endl;
```

Selecting everything and commenting it using the simple block method (`ggVG\cm`) leaves me with this:

```c
/* int n = 3;                                         
/*call function asynchronously:*/
std::future<bool> fut = std::async (is_prime,n);
std::cout<< n << std::endl; */
```

**Comment by alerque** [comment]
Oh, I see what's different. I have `let g:NERDSpaceDelims = 1` set in my RC file. If I remove that (or add spaces to the linewise comment) it recognizes the nested comment and makes it a placeholder. It wasn't before because it didn't have the requisite spaces. I guess that means we can close this for now (with a better solution to come for languages that actually support nesting via #151). Thanks for the review.

If anybody has anything to add or a case that isn't working, please comment and we'll reevaluate.
