### ISSUE TITLE
php multiline bug in visual mode

### ISSUE THREAD

**Issue by roman4e** [scrooloose/nerdcommenter#174]
Let I have a little code:
```php
$obj->ping();
$obj->info();
$obj->getSpecList();
$obj->oneRequest("something");
```
So if I select these lines in visual mode and press &lt;leader&gt;cc, I get 
```php
/*$obj->ping();*/
//$obj->info();
//$obj->getSpecList();
/*$*/obj->oneRequest("something");
```
instead of expected
```php
//$obj->ping();
//$obj->info();
//$obj->getSpecList();
//$obj->oneRequest("something");
```
An expected behavior is provided only by binding &lt;leader&gt;c&lt;space&gt; 'toggle comment'

The same behavior to unexpected is while calling nested commenting

**Comment by alerque** [comment]
This appears to have been fixed at some point as it works as expected with the example you give. If this is still a problem for you please comment and I'll re-open this for review.
