### ISSUE TITLE
js comments in an html file

### ISSUE THREAD

**Issue by xiejie** [scrooloose/nerdcommenter#175]
```javascript
<script>
  alert('test')
</script>

comment as 
<script>
 <!--  alert('test') -->
</script>

I went 
<script>
 // alert('test') 
</script>
```

**Comment by amadeus** [comment]
:+1: This issue is pretty annoying and would be nice to have a fix for.

**Comment by monofonik** [comment]
Was this closed / fixed or just closed?

**Comment by aemonge** [comment]
It's still super annoying, so I think just closed

**Comment by alerque** [comment]
This is a duplicate of #17 (and also mentioned in #225). @monofonik anad @aemonge please subscribe to that ticket to track progress. This is a non-trival change and I'd love to see a contribution to the project that makes it work, but no promises as to when I might have the time.

**Comment by aemonge** [comment]
ty
