### ISSUE TITLE
Support lazy loading for nerdcommenter

### ISSUE THREAD

**Issue by chilicuil** [scrooloose/nerdcommenter#176]
Some recent vim plugin managers allow lazy loading with a syntax similar to this:

    Bundle 'scrooloose/nerdcommenter', {'on': '<Plug>NERDCommenterToggle' }
    map <leader>c<space> <Plug>NERDCommenterToggle

Unfortunately due to the way nerdcommenter starts it's not possible to load it lazily, when doing so it fails with something like this:

```
Error detected while processing function NERDComment..<SNR>43_IsInSexyComment..<SNR>43_FindBoundingLinesOfSexyCom..<SNR>43_Multipart.
.<SNR>43_Right:
line    3:
E121: Undefined variable: b:NERDCommenterDelims
E15: Invalid expression: has_key(params, 'alt') ? b:NERDCommenterDelims['rightAlt'] : b:NERDCommenterDelims['right'] 
line    5:
E121: Undefined variable: delim
E15: Invalid expression: delim == ''
Error detected while processing function NERDComment..<SNR>43_IsInSexyComment..<SNR>43_FindBoundingLinesOfSexyCom..<SNR>43_Multipart.
.<SNR>43_Right:
line    3:
E121: Undefined variable: b:NERDCommenterDelims
E15: Invalid expression: has_key(params, 'alt') ? b:NERDCommenterDelims['rightAlt'] : b:NERDCommenterDelims['right'] 
line    5:
E121: Undefined variable: delim
E15: Invalid expression: delim == ''
```

That's because there hasn't been enough time to call `SetUpForNewFiletype`, which is called after autocommands.

```
augroup NERDCommenter

    "if the user enters a buffer or reads a buffer then we gotta set up
    "the comment delimiters for that new filetype
    autocmd BufEnter,BufRead * :call s:SetUpForNewFiletype(&filetype, 0)

    "if the filetype of a buffer changes, force the script to reset the
    "delims for the buffer
    autocmd Filetype * :call s:SetUpForNewFiletype(&filetype, 1)
augroup END
```

A temporal workaround it to call `SetUpForNewFiletype` manually just at the end of NERD_commenter.vim

```
inoremap <silent> <plug>NERDCommenterInsert <SPACE><BS><ESC>:call NERDComment('i', "insert")<CR>
call s:SetUpForNewFiletype(&filetype, 1)
```

Anyway probably there is a better a way, so I left it here for your consideration.

Thanks for the great plugin!

**Comment by alerque** [comment]
Thanks for the contribution @chilicuil. I don't know of a better solution and I've hit this issue myself so I've gone ahead and implemented this hack. If anybody comes up with a better solution I'm all ears...
