### ISSUE TITLE
How to add a space between the comment delimiter

### ISSUE THREAD

**Issue by twmht** [scrooloose/nerdcommenter#185]
hi,

This is not a issue.

I want to add a space between comment delimiter, but I don't know how to do that.

For example,

```
int version;
```
after comment it with  ```<leader>cc```

it will become 
```
//int version
```

But what I want is 
```
// int version
```
There is one space after the delimiter

Here is a another example

```
/*int version*/
```

But what I want is 

```
/* int version */
```

There is a space before and after the delimiter.

Is it possible to configure that in nerdcommenter?

Thank you!

**Comment by rosshadden** [comment]
This is supported and explained in the docs.

https://github.com/scrooloose/nerdcommenter/blob/master/doc/NERD_commenter.txt#L668-L684

**Comment by twmht** [comment]
@rosshadden 

awesome!!!

Having ```let NERDSpaceDelims=1``` would do the trick.

Thank you @rosshadden  :)
