### ISSUE TITLE
Do not consider blank lines uncommented when toggling

### ISSUE THREAD

**Issue by DelvarWorld** [scrooloose/nerdcommenter#194]
If you make a visual selection of a **commented** block of text, **then include an empty line above the selection** and hit `<leader>c<space>` to toggle comments, NERDCommenter appears to think the blank line is uncommented, and double-comments the selected block.

It would be much nicer if the algorithm that determines if something is commented (which appears to use the first line of a visual selection) read lines until one of them wasn't blank.

**Comment by alerque** [comment]
This actually is a bit of a catch 22. It works as expected for _multi-line comments_. If you use a multi-line syntax, including a blank line above a selection does the right thing already. It's only when using line-wise delimiters in leu of block delimiters that this seems to be a problem. I'm not sure how the logic for this would work given that a line-wise check for comments wouldn't find one (which is correct).

**Comment by alerque** [comment]
@DelvarWorld Somebody has stepped up and implemented something like this. Would you be able to checkout the code from Pull Request #250 and see it it works for your use case and offer any feedback you  make have?

**Comment by alerque** [comment]
This is not an option you can set if you want this behavior. Thanks to @alexconst for the implementation.
