### ISSUE TITLE
How to comment/uncomment code using NERD Commenter?

### ISSUE THREAD

**Issue by tastyminerals** [scrooloose/nerdcommenter#205]
I need to comment/uncomment blocks in my code. I have read **Usage** section for NERD Commenter but I have still no clue what to do in order to comment/uncomment the code.

What does `[count]<leader>cc |NERDComComment|` notation mean? How difficult will it be to provide a simple translation of the lines above?

**Comment by brianpeiris** [comment]
@tastyminerals "Leader" is a common concept in Vim: http://usevim.com/2012/07/20/vim101-leader/

**Comment by Neats29** [comment]
Just means: \cc
