### ISSUE TITLE
Managing Rust comments

### ISSUE THREAD

**Issue by Ilphrin** [scrooloose/nerdcommenter#206]
Hi,

I started to learn [Rust](https://www.rust-lang.org/) language, and I noticed that your plugin doesn't work totally with it. There is [3 kinds of comments](https://doc.rust-lang.org/book/documentation.html) in Rust, nerdcommenter seems to use by default // as a symbol which is correct with Rust for the classical comments, but there isn't a way to use the 2 other kinds of comments.
The second way is using /// which is used to generate common documentation.
And the last way is using //!  which is used to generate module documentation.

I really don't know much about coding Vim plugins, but it seems in your code that when adding a new language you can have 'left' and 'leftAlt' property. But Rust needs a third command, is there any way to have this in your plugin?

By the way, thanks a lot for you awesome plugin! And if it is not possible to have three types of comments that's ok I think I won't die of this x)

**Comment by alerque** [comment]
At this time I don't think there is a way to setup three delimiters, but I have  added the triple slash syntax as the alternate for Rust. The module documentation string is more of a Rust language feature than it is a comment format—actually both of these are just overloaded comment operators, but at least now one of them should be easy to get to. I hope that helps.

**Comment by Ilphrin** [comment]
Ok great! It's ok I thought too that it would not be possible to add that kind of comment, but the triple slash syntax is enough to be comfortable ;) Thanks!
