### ISSUE TITLE
Stack toggle with left-alignment

### ISSUE THREAD

**Issue by atsepkov** [scrooloose/nerdcommenter#210]
I mapped NERDComment as follows:

    map <leader># :call NERDComment(0,"toggle")<C-m>

Which works as expected except that it violates my own debug convention: *temporarily-commented line should have comment start before indentation*. This convention allows to easily parse the file visually and determine which lines need to be uncommented/removed before checking in the code (because they won't match the indent).

I noticed that NERDCommenter also has a `LeftAlign` option, which does exactly the kind of alignment I want. Problem: it doesn't toggle. How can I stack the two options?

**Comment by alerque** [comment]
As of #24 being merged there is now a config option for this. Try `let g:NERDDefaultAlign = 1` or similar, and see the help documentation for details.
