### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by KidA424** [scrooloose/nerdcommenter#258]
The readme file has these lines:

    " Align line-wise comment delimiters flush left instead of following code indentation
    let g:NERDDefaultAlign = 'left'

But I think that 'left' should actually be replaced with 'start'.

**Comment by alerque** [comment]
Key @KidA424 thanks for the suggestion. The documentation could probably be clearer on this point, but this isn't actually a typo. The `left` and `start` modes are different in that both of them align left without following code indentation, the difference is one starts at the current indentation and the other is hard wired to start at the beginning of the line. Both should end up left aligned as described.

**Comment by KidA424** [comment]
Thanks for letting me know!
