### ISSUE TITLE
Block format comment layout with box drawing effects

### ISSUE THREAD

**Issue by xavierartot** [scrooloose/nerdcommenter#261]
Hi,
how can I have this kind comment:
https://github.com/mathaywarduk/simple-sass-framework/blob/master/assets/sass/screen.scss
Thank you

**Comment by alerque** [comment]
By using a different plugin.

The closest thing this plugin offers to that is the "sexy" comment  scheme included with most languages that  starts and ends  with the languages block comment syntax and fills it with related characters in between at a constant indent level. For example in Lua I get something like this:

```Lua
--[[ commented out content
   [ commented out content
   [ commented out content
   [ commented out content ]]
```

Beyond that sort of layout (with a few options documented in the help system) you are on your own. If you wanted to add it as a feature, a pull request might be accepted but I don't  plan to implement this directly. There are, however, plugins already out there specifically for formatting those kind of blocks.

**Comment by alerque** [comment]
See also #161 for a (very) incomplete implementation somebody started that covers part of this.
