### ISSUE TITLE
React - jsx

### ISSUE THREAD

**Issue by xavierartot** [scrooloose/nerdcommenter#280]
Hi,
I'm a huge fan, but with React and jsx it doesn't work.
Thanks

**Comment by alerque** [comment]
Are they listed in the file type matrix? Do you mean the file types aren't supported yet or they aren't working _properly_?

**Comment by chrisnojima** [comment]
Hi,

Maybe I'm misunderstanding how the vim filetype declaration works but I have my .js files set as javascript.jsx so I can get js and jsx formatting.  These files have a mix of plain js and blocks of jsx (typical react files) yet with this change all comments are of the form `{/* to comment out */}`. But this doesn't work on plain js. For example i see this

```
// This is correct
const render = () => (
  {/* <div /> *}
)

// This is incorrect
{/* const a = 'hello' */}

```

**Comment by alerque** [comment]
@chrisnojima Vim doesn't provide (at least not readily) context sensitive information about what type of language block you are it. As far as NerdCommenter is concerned this is pretty much a one shot deal. Either the filetype is plain JS (in which case you get  plain JS comments) or it is JSX, in which case you  get React style comments. It doesn't try to parse the surrounding lines to toggle back and forth between language modes.

There are several languages for which this would be desirable, but I'm not aware of a good way to implement this yet. I would suggest opening this as a separate issue (if we don't  have one already) as a potential improvement. I'd be happy to see a contribution to this effect.

In the mean time I don't thing you have an easy option to handle this other than  changing the file type or overriding the JSX comment type to generate plain JS comments.

**Comment by amadeus** [comment]
Ok, IMO the fix that got merged in for this should be reverted.

JSX files are just Javascript really, with some specialized syntax every once in a while. This current change breaks commenting completely for JSX files. My vote would be to revert this change and just force people to comment manually within JSX scope.

Take this super simplified example:


```jsx
import React, {PureComponent} from 'react';

class MyComponent extends PureComponent {
    handleClick() {
        console.log('You\'ve clicked the element!');
    }

    render() {
        return (
            // The only actual JSX witin the file
            <div onClick={() => this.handleClick()}>Example JSX syntax</div>
        );
    }
}

export default MyComponent;
```

It's now impossible to use NERDCommenter anywhere within the file, EXCEPT within that single one line in the return statement.

**Comment by argshook** [comment]
totally agree with @amadeus, this change took me by surprise. I very rarely comment actual jsx code.

to bring back previous behaviour one can override delimiters for `javascript.jsx` filetype to be same as for `javascript`:

```vim
let g:NERDCustomDelimiters = { 'javascript.jsx': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' } }
```

ugly but you know, works

**Comment by alerque** [comment]
Thanks for the feedback @chrisnojima, @argshook and @amadeus. I've reverted the commit that added JXS "support" pending a more robust solution.

**Comment by Addisonbean** [comment]
I use this in my `.vimrc`:

```
let g:NERDCustomDelimiters={
	\ 'javascript': { 'left': '//', 'right': '', 'leftAlt': '{/*', 'rightAlt': '*/}' },
\}
```

That way, I can use the alternate style for jsx comments when needed, while still using normal js comments as default comment style.

**Comment by alerque** [comment]
@Addisonbean Those alternate delimiters are already in the default javascript language definition. You shouldn't need to add this manual override, it should be ready for that usage out of the box.

**Comment by amadeus** [comment]
@Addisonbean these alts are different - in this override they include `{`

**Comment by alerque** [comment]
@amadeus Oh my bad. Sorry I didn't inspect that closely enough.

**Comment by alerque** [comment]
For those using Vim to program in React please see PR #393 and comments on our support for these filetypes in 41d31b3.

**Comment by diegoulloao** [comment]
> @Addisonbean these alts are different - in this override they include `{`
> 
> Javascript in this plugin is just:
> 
> ```
>     \ 'javascript': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
> ```

How do you use it? It make anything if I trigger the comment command

**Comment by Goku-kun** [comment]
Hey, @diegoulloao!

You can trigger alternative delimiters using `<leader>ca`. You can read more about it in the README.md description.

![image](https://user-images.githubusercontent.com/44740407/214015916-3d4eeb90-c846-4d4f-9ebc-f95b2a5103c2.png)
