### ISSUE TITLE
right delimiters in code block of markdown

### ISSUE THREAD

**Issue by silverHugh** [scrooloose/nerdcommenter#308]
Is that possible to detect the right delimiters in the code block of markdown.

For example,

    ``` js
    /* This is what I want, */
    ```

    ``` js
    <!-- but this is the given. -->
    ```

**Comment by alerque** [comment]
No, handling comments of different types of  languages in one file is not supported. See #17 and subscribe to track the feature request for this. In the mean time you can `:set ft=javascript` or whatever to set the file type while you work in a code block like that.
