### ISSUE TITLE
Add custom comment character?

### ISSUE THREAD

**Issue by MikeDacre** [scrooloose/nerdcommenter#313]
I use snakemake with this syntax file: https://bitbucket.org/snakemake/snakemake/raw/master/misc/vim/syntax/snakemake.vim

The file is basically python, with some modifications. My vimrc contains:

```vim
au BufNewFile,BufRead Snakefile set syntax=snakemake
au FileType snakemake let Comment="#"
let NERDSpaceDelims=1
let g:NERDCustomDelimiters = {
      \ 'py' : { 'left': '#' },
      \ 'snakemake' : { 'left': '#' },
      \ 'sshconfig' : { 'left': '#' },
      \ 'sshdconfig': { 'left': '#' }
      \ }
map <Leader>cv <plug>NERDCommenterToggle
```

Comments starting with '#' are correctly formatted as comments by vim with this setup.

When editing `Snakefile` files, `<Leader>cv` still results in `/* <comment> */`

Any ideas?

**Comment by MikeDacre** [comment]
Modifying `nerdcommenter/plugin/NERD_commenter.vim` to contain `'snakemake' : { 'left': '#' }` also fails. The ugly C comments still are used.

**Comment by khughitt** [comment]
By default, no filetype is associated with Snakefiles. The custom comment settings do work when it is specified manually, e.g.:

```
au BufNewFile,BufRead Snakefile set filetype=snakemake
au BufNewFile,BufRead *.snakefile set filetype=snakemake
```

**Comment by alerque** [comment]
Even though VIM does not have an upstream filetype defined for this yet it seems pretty obvious that *snakemake* will be the name if/when it does. I've gone ahead and added support of of the box in this plugin.

Note that this will not work unless you set the filetype yourself. You can either do that with an autocommand as @khughitt points out, or my recommendation would be to use something like [`vim-snakemake`](https://github.com/ibab/vim-snakemake) that detects the filetype and adds syntax highlighting.

**Comment by khughitt** [comment]
Great! Thanks for adding support. And good call on the plugin :+1:
