### ISSUE TITLE
Please consider supporting vue

### ISSUE THREAD

**Issue by Dcryfm** [scrooloose/nerdcommenter#322]
In the `vue` file, both the code in the `script tag` and the ` style tag` are commented, using html comment.

**Comment by mblarsen** [comment]
I don't recall where I got this, so I cannot give credit where it is due. But adding this hook will do the trick. 

```vim
function! NERDCommenter_before()
  if &ft == 'vue'
    let g:ft = 'vue'
    let stack = synstack(line('.'), col('.'))
    if len(stack) > 0
      let syn = synIDattr((stack)[0], 'name')
      if len(syn) > 0
        exe 'setf ' . substitute(tolower(syn), '^vue_', '', '')
      endif
    endif
  endif
endfunction
```

See recording https://asciinema.org/a/xbEFLoNTRoRr6DTWt3GzC9aua

**Comment by mblarsen** [comment]
It changes the file type based on the syntax at the current location so that NERDCommenter can toggle the right comment style and then swaps it back afterwards. 

There are some limitations to this which is why there is no generic solution (AFAIK). See #17 for an explanation.

**Comment by Dcryfm** [comment]
@mblarsen Thank you very much, I will try it. Already a similar and better issue #17, then I closed the issue.

**Comment by mauchchhash** [comment]
@mblarsen The script works for the js block perfectly but it glitches on the html block. In my case it sometimes wraps the current html line in `/* <my html code> */` when I want it to do `<!-- <my html code> -->`. I think it would be excellent if this feature is implemented natively.
And by the way, here's the credit for you code:[doc](https://github.com/scrooloose/nerdcommenter/blob/master/doc/NERD_commenter.txt#L413) :)

**Comment by Gbeschbacher** [comment]
It has worked for me quite a while and stopped working recently. I'm a noob when it comes to debugging vim scripts but as far as i can tell the hooks are still working properly. In my Vue SFC the blocks are still identified as htmltags or javascript but somehow the comment-type is always html-style (). I somehow think that it's due do my vim version (8.2.2311).

Anybody got an idea how to get this working again? I don't want to switch to another plugin or anything like that
