### ISSUE TITLE
Wrong comment format for yml files

### ISSUE THREAD

**Issue by 23tux** [scrooloose/nerdcommenter#326]
When I try to comment in a *.yml file, it looks like this

```<%# my_key: "foobar" %>```

This is invalid (Psych is complaining about a broken yml file). However, in a *.yaml it works

```# my_key: "foobar"```

I tried to add a custom delimiter

```let g:NERDCustomDelimiters = { 'yml': { 'left': '#' } }```

but it still uses `<%#` to comment lines. Any ideas, why the custom delimiter doesn't work? Or would it be possible to extend the plugin with the `yml` file ending?

**Comment by alerque** [comment]
The plugin does not look at file endings, it looks at the value of the `filetype` setting.  What you need is not something to tell this plugin about YAML, you need something to tell VIM that *.yml files are probably YAML.

The simplest thing is just to `:set ft=yaml` yourself. However if you might be missing out on other language features like syntax highlighting. I generally recommend using a plugin like [vim-polyglot](https://github.com/sheerun/vim-polyglot) to expand the base set of available file types and syntax highlighting. In your case however I think YAML should be built in. I know it is on Neovim, for examlpe if I look at `/usr/share/nvim/runtime/filetype.vim` there is a line like this:

```vim
au BufNewFile,BufRead *.yaml,*.yml      setf yaml
```

A line like that in your config to set the filetype for the extension should do the trick for you too, but you should also look into why this isn't happening already. You probably are clobbering some automatic process that would normally be done for you.
