### ISSUE TITLE
Option to specify number of spaces to prepend appended comment with

### ISSUE THREAD

**Issue by shammellee** [scrooloose/nerdcommenter#328]
I prefer my appended comments to start 2 spaces after the line. Any way to do this?

```c
int * get_codes()
{
  static int codes[6] = {24, 38, 43, 87, 42, 54};  // Nuclear codes

  return codes;
}
```

**Comment by alerque** [comment]
Personally I think that's silly, but of course you can do whatever you like with your own code. Check out the source code starting about line 44.

```vim
let s:spaceStr = '  '
```

**Comment by alerque** [comment]
Well I think PEP8 is silly, but that's my prerogative to think. Like I said you're free to do whatever, I won't stop you from using this plugin to produce 5 spaces before comments if that's what you want. There is a provision in the code to change this behavior by setting a variable in your vim configuration file. So happy PEP8ing to you all, and may your editor windows always be at least 256 characters wide ;-)

**Comment by zgpio** [comment]
Modify `s:spaceStr` can not solve this problem, it means `before inline comment`, not after.
