### ISSUE TITLE
change maker symbol

### ISSUE THREAD

**Issue by ghost** [scrooloose/nerdcommenter#329]
Hi, is there any way to change the default marker symbol ?
Ex : `*` to `**` in C

**Comment by alerque** [comment]
Please see `:help nerdcommenter` or more specifically in this case `:help NERDCustomDelimiters`.

**Comment by albfan** [comment]
Looks like marker con sexy comments are selected using last char on longest left comment. In case of C comments is directly set as '*'

so as an example, 

```
let g:NERDCustomDelimiters = {
        \ 'xml': { 'left': '<!--', 'right': '-->', 'leftAlt': '<!-- ', 'rightAlt': '-->' },
        \ 'html': { 'left': '<!--', 'right': '-->', 'leftAlt': '<!--', 'rightAlt': '-->' }
    \ }
```

without set alt delimns for xml and html, you can use this trick to get an space as marker.

Still that's undesired, and one might want to have an empty marker.

Could make sense to allow:

```
let g:NERDCustomDelimiters = {
        \ 'xml': { 'left': '<!--', 'right': '-->', 'marker': ''},
        \ 'html': { 'left': '<!--', 'right': '-->', 'marker': ''},
    \ }
```

so user explicitly set the marker?

**Comment by alerque** [comment]
If you have something to pose as a question or feature request or issue report, open a new issue @albafan.

**Comment by albfan** [comment]
Looks to me the issue was valid and not resolved. I just try to complete an already existing issue so others can find it. #546 should fix it although I need to add 'nested' to avoid  an error plugin logic detects

```
let g:NERDCustomDelimiters = {
        \ 'c': { 'left': '/*', 'right': '*/', 'marker': '**', 'nested': 1}
    \ }
```

I'm not sure how nerdcommenter decides if use '//' or '/* */' my expectations would be to only set

```
let g:NERDCustomDelimiters = {
        \ 'c': {  'marker': '**'}
    \ }
```
