### ISSUE TITLE
NERDRemoveExtraSpaces work errer with NERDDefaultAlign = 'left'

### ISSUE THREAD

**Issue by fcying** [scrooloose/nerdcommenter#335]
vimrc
```
set nocompatible
set mouse=n
set runtimepath+=~/.vim/plugged/nerdcommenter
filetype plugin indent on
syntax enable

let g:NERDRemoveExtraSpaces = 1
let g:NERDDefaultAlign = 'left'

let g:a=0
if g:a == 0
  let b = 1
endif
```
reproduce ways:
comment if code use `\cc`
```
"if g:a == 0
"  let b = 1
"endif
```
uncomment if code use `\cu`
```
if g:a == 0
 let b = 1
endif
```

the space before `let b = 1` miss one.
if I remove `let g:NERDDefaultAlign = 'left'`, it work fine.

**Comment by fcying** [comment]
if I set `let g:NERDSpaceDelims = 1`, it work fine.

Is this option(NERDRemoveExtraSpaces ) unused now?

If I set:
```
let g:NERDRemoveExtraSpaces = 0
let g:NERDSpaceDelims = 1
```
It can remove ExtraSpaces also.

**Comment by fcying** [comment]
I just deleted the setting of `NERDRemoveExtraSpaces` and it has no effect on it.

**Comment by alerque** [comment]
The `g:NERDSpaceDelims` setting will effect this for sure, but if you uncomment code with that setting on that was commented with it off (or manually) then you will run into this situation where it removes too much.
