### ISSUE TITLE
NERD commenter not working, no commands listed, but appears in loaded scripts?

### ISSUE THREAD

**Issue by CaerphillyMediaLtd** [scrooloose/nerdcommenter#347]
Arch Linux
Neovim v0.3.1 (also tried with Vim 8.1)

I've installed NERDCommenter via Vim-Plug but it doesn't seem functional. I can run the help commands and see the associated documentation, I can see it has bound the mappings to the correct keys, and I can see it in the loaded scripts. But when I try to press the keys nothing works. I've also tried running manual commands like :NERDComComment, but nothing comes up on the autocomplete and they all register as unknown commands.

**Comment by johnzim** [comment]
If you recently moved from Vundle or a different package manager to vim-plug, make sure you have the right plugin listed.. The old one used vimscripts and had the repo name `The-NERD-commenter`

```
Plug 'scrooloose/nerdcommenter'
```

then re `:source` and try another `PlugInstall` 


After that one final `:source` should do it :)

**Comment by alerque** [comment]
I have used Neovim + Vim-Plug on Archlinux as my primary platform on half a dozen computers for years, and it seems functional to me. In fact dozens of people I know have this combination. As @johnzim suggested I suggest you probably have vim-plug setup incorrectly. We would need more details about your config to confirm this, but until further evidence that something is wrong with the plugin itself I don't think there is an issue to be fixed.
