### ISSUE TITLE
filetype:"py" has two space between '#' and text when use vim command "vs" from a another filetype window to "py" window

### ISSUE THREAD

**Issue by termanary** [scrooloose/nerdcommenter#351]
When I am editing a file whose filetype is "xxx",I use a vim command : 
```
vs b.py
```
When use NERDcommenter , NERDcommenter uses two spaces between '#'
and text , which is a different action compare with before.
I find the problem is due to the following code : 
```
filetype indent plugin on

let g:NERDSpaceDelims = 1
let g:NERDAltDelims_xxx = 1

" I find that the next line will not take effect to this problem,
" let g:NERDAltDelims_python = 1/0
```
I try "c","cpp","vim" for "xxx".The problem exists exactly.
But I change the filetype "py" to "v" ,"c","cpp", the filetypes I change acts correctly .
Just filetype : "py" acts like this .

I do not know what problem is ? How to solve it ?

**Comment by alanwei0** [comment]
me too

**Comment by alanwei0** [comment]
@termanary https://github.com/scrooloose/nerdcommenter/issues/202
This may be helpful

**Comment by termanary** [comment]
Thanks for attention.I solve this by modifying NERDcommenter.vim.
