### ISSUE TITLE
Enhancement request: option to left align comment delimiters

### ISSUE THREAD

**Issue by mcocdawc** [scrooloose/nerdcommenter#357]
It would be great to have a ``leftmost`` (or something related) option for the alignment of columns.
To force an insertion of comment markers in the first column.
I am especially thinking about Fortran77 where 
```
       integer :: i
       subroutine f
       end f
```
should become:
```
!       integer :: i
!       subroutine f
!       end f
```
Align left does not solve the problem.

**Comment by alerque** [comment]
See commit https://github.com/afro85/nerdcommenter/commit/695d4bd2442e995c43b96e89e01e542dd93da0f5 which looks like it might be related to this.

**Comment by bew** [comment]
Isn't it what `let g:NERDDefaultAlign = 'start'` is for?

**Comment by mcocdawc** [comment]
Thanks for letting me know! ;-) I am pretty sure, that this was not implemented when I opened the issue.
