### ISSUE TITLE
does it support kivy?

### ISSUE THREAD

**Issue by zhonghuabao1** [scrooloose/nerdcommenter#361]
the correct comment is "#" for kivy file (**.kv), but it use "/* */"

**Comment by zhonghuabao1** [comment]
Oh, I see, `let g:NERDCustomDelimiters = {'kivy': {'left': '# '} }`

**Comment by alerque** [comment]
You are correct you can add your own file format supports like that, but you can also add and contribute them to this project. I just added kivy support out of the box for you. If you prefer the space after the comment delimiter you can set this:

```vim
let g:NERDSpaceDelims = 1
```

**Comment by zhonghuabao1** [comment]
thanks for ans, I will try it .
