### ISSUE TITLE
markdown commenting broken

### ISSUE THREAD

**Issue by dylan-chong** [scrooloose/nerdcommenter#373]
If i try to comment `sdlkfjaskldfjdsaf` with `gc` in a `.md` file, i get `{% comment %} sdlkfjaskldfjdsaf {% endcomment %}` rather than `<!-- sdlkfjaskldfjdsaf -->`

my config:

```
" let g:NERDDefaultAlign = 'start'
let g:NERDRemoveExtraSpaces = 0
let g:NERDTrimTrailingWhitespace = 1
let g:NERDSpaceDelims = 1
nmap gc <leader>c<space>
vmap gc <leader>c<space>
```

**Comment by dylan-chong** [comment]
seems to be caused by `vim-polyglot`

**Comment by alerque** [comment]
Check what your file type is getting set to after you open a markdown file:

```vim
:set ft
```

**Comment by dylan-chong** [comment]
oops forgot to close this. see my comment above
