### ISSUE TITLE
doesn't get rid of leading whitespace

### ISSUE THREAD

**Issue by theonlygusti** [scrooloose/nerdcommenter#375]
Running `<leader>c<Space>` on a line like

```py
# this comment
```

turns it into 

```none
  this comment
```

with leading whitespace.

How can I stop this behaviour?

I want the leading whitespace in comments like these

```
// <-- a space
-- another comment style
; another
" another
```

to also be removed and re-inserted when using nerdcommenter

**Comment by alerque** [comment]
This works for me out of the box.

What do you have `g:NERDSpaceDelims` and `g:NERDRemoveExtraSpaces` set to?

**Comment by theonlygusti** [comment]
```
:echo g:NERDSpaceDelims
0
:echo g:NERDRemoveExtraSpaces
0
```

@alerque

**Comment by alerque** [comment]
You need to configure your preferred method of handling spaces. Right now you have them disabled. It sounds like you probably want both of those things enabled, but mix and match to your preference.

```vim
let g:NERDSpaceDelims = 1
let g:NERDRemoveExtraSpaces = 1
```
