### ISSUE TITLE
Can't find the default <Leader> mapping in help file

### ISSUE THREAD

**Issue by Nagidal** [scrooloose/nerdcommenter#384]
I almost had to give up on this plugin because I could not find which key is the `<Leader>`. In the whole :help nerdcommenter I could not find that it is mapped to '\\' by default. Only [this comment](https://stackoverflow.com/a/1676775/9235421) on stackoverflow says it. It should be right at the beginning of the help in the functionality summary.

**Comment by Nagidal** [comment]
Thanks, I'll try to create a pull request later. I had no idea that <Leader> is defined in vim and in vim help, I thought it's just a nerdcommenter's thing.

**Comment by alerque** [comment]
No, `<Leader>` is pretty much the _de facto_ way for plugins to define keymaps so they don't step on common native mappings. Probably 70% of vim-plugins you run across will use this, as well as many user configs you'll find online. It isn't quite universal, but it's kind of expected users will know about this.

I don't mind adding something to the help, but keep it short and keep in mind it isn't universally `\`, that's just tho most common default out of the box. Probably the best thing to do is just add a quick link to the `:help Leader` section in the help, and in the README just comment that <kbd>&lt;Leader&gt;</kbd> is whatever vim is configured to use.

**Comment by Nagidal** [comment]
Pull request created.
