### ISSUE TITLE
e42 no errors

### ISSUE THREAD

**Issue by zhangyl4991** [scrooloose/nerdcommenter#387]
sometimes when i want to comment a line in gvim-gtk2, i got message "e42: no errors", but comment multipe lines and uncomment both work fine. In addtion, vim works fine.
gvim version: 7.2
Included patches: 1-1689
Extra patches: 8.0.0056

**Comment by alerque** [comment]
What comment command and mapping are you using? It sounds like you're actually triggering something besides just the comment command.

**Comment by zhangyl4991** [comment]
I tried <Leader>cc and <Leader>cn both.

**Comment by alerque** [comment]
I suggest checking what the key sequences of your bindings do on your system with this plugin _disabled_.

**Comment by zhangyl4991** [comment]
I remap the key sequences to quickfix command...
thanks!
