### ISSUE TITLE
[Request] Comment using vim marks

### ISSUE THREAD

**Issue by a5a** [scrooloose/nerdcommenter#389]
The plugin is great for what it does, so thank you to the maintainers for this.

I have noticed in my own workflow, that it would be a great addition to be able to choose the region to (un)comment using vim marks (as opposed to counting the lines), as I sometimes am dealing with larger blocks of code that I want to toggle on or off.

Would it be possible to add this functionality into the plugin? I searched the docs and the issue tracker, but couldn't find mention of this in either one, so I decided to open this ticket to discuss the suggestion.

Cheers

**Comment by alerque** [comment]
The way vim commands work is they provide you the building blocks to assemble in any manner you like. You already have all the tools to do what you want.

* You can set marks.
* You can visually by jumping to a mark.
* You can comment the visual selection (using a function provided by this plugin).

If you want to combine the last two steps into a single keystroke, just create a map a key to an action that does both those things in sequence, probably using some mark name that you commonly use for the purpose.
