### ISSUE TITLE
c and c++ have the different comment style

### ISSUE THREAD

**Issue by YvesZHI** [scrooloose/nerdcommenter#394]
For the code `int i = 1;`, in the C file, when I type `\cc`, this line will become `/* int i = 1; */`, but in the CPP file, `\cc` will make this line like this: `// int i = 1;`.

Why do they have different style? How can I make them the same?

It seems that this is because the line 112 and the line 130 are different here: https://github.com/scrooloose/nerdcommenter/blob/master/plugin/NERD_commenter.vim

Here is my config:

```
let g:NERDSpaceDelims=1
let g:NERDCompactSexyComs=1
let g:NERDDefaultAlign = 'left'
let g:NERDAltDelims_java=1
let g:NERDCommentEmptyLines=1
let g:NERDTrimTrailingWhitespace=1
let g:NERDToggleCheckAllLines=1
```

**Comment by alerque** [comment]
While both languages understand both styles of comments, the difference in defaults has to do with the most widely adopted style guides for each language respectively.

You are welcome to setup your rc/init file with an array of file types that you would like to add or override the build in defaults. For example to make them both something odd with lots of extra stars and slashes you could override the defaults:

```vim
let g:NERDCustomDelimiters = {
  'c': { 'left': '/*****','right': '****/', 'leftAlt': '////' },
  'cpp': { 'left': '/*****','right': '****/', 'leftAlt': '////' },
}
```

Note you could reverse what was primary and what was secondary styles as well.
