### ISSUE TITLE
CUDA delimiters different from C/C++ delimiters

### ISSUE THREAD

**Issue by horst5000** [scrooloose/nerdcommenter#395]
CUDA uses /* .. */ by default and // as alternative while for nearly other C-ish languages it's the other way round. Since people working with CUDA often use C/C++ in parallel the commenting behavior is rather confusing. Sure I can make custom delimiters, but I cannot imagine that this was actually intended.

**Comment by alerque** [comment]
Thanks for the info @horst5000, I'd be happy to merge that if you'd like to submit the change an a PR.

**Comment by horst5000** [comment]
Here it is. Thanks for the quick response!
