### ISSUE TITLE
Remapping leader not tracked

### ISSUE THREAD

**Issue by kprussing** [scrooloose/nerdcommenter#399]
Consider the following minimal `vimrc` using `vim`'s native package manager:

    set nocompatible
    filetype plugin on
    packadd nerdcommenter
    let mapleader = ","

With this ordering, the plugin macros work with the default leader `\`.  On the other hand, if the order is

    set nocompatible
    filetype plugin on
    let mapleader = ","
    packadd nerdcommenter

then `,` is respected as the leader.  The first order worked with `pathogen` but stopped working when I switched to the native package manager.  Is this something that can be changed at the package level?

**Comment by alerque** [comment]
This is pretty surprising, but I think this is going to turn out to be a bug in the native package manager. This plugin isn't doing anything too fancy. Whet it sets up bindings it uses the `<leader>` key syntax to refer to the current leader key (whatever that is). I doesn't look at what `mapleader` is set to or cache the value or anything like that.

I suspect you'll find the same behavior in _any_ plugin that uses `<leader>` bindings.

**Comment by kprussing** [comment]
It looks like you are correct. I opened an issue over on the [vim page](https://github.com/vim/vim/issues/5071).

**Comment by alerque** [comment]
To answer the question about why plug-in managers surface different behavior … it probably has to do with autoloading on demand. I define all of my plugins before my mapleader in my config but vim-plug apparently doesn't activate them until it parses the rest of my rc file. Vim's builtin has taken a different approach. Additionally many plug-ins themselves setup autoload only for specific filetype hooks, so bindings might not be even instantiated until loading a buffer.
