### ISSUE TITLE
Enable aligning toggled comments

### ISSUE THREAD

**Issue by pedorro** [scrooloose/nerdcommenter#49]
Add option to left-align the comment symbol rather than put it just before the first character.  For example...

allow this:

```java
//    public int getId() {
//        return id;
//    }
```

instead of this:

```java
   // public int getId() {
       // return id;
   // }
```

I believe the first option above is more readable

Possible implementation:

```vim
function s:CommentLinesToggle(forceNested, firstLine, lastLine)
...
            if g:NERDAlignCommentToggle
                let theLine = s:AddLeftDelimAligned(s:Left({'space': 1}), theLine, 0)
            else
                let theLine = s:AddLeftDelim(s:Left({'space': 1}), theLine)
            endif
```

**Comment by hellolj** [comment]
love this

**Comment by ben-rosio** [comment]
:+1:

**Comment by serge-stroobandt** [comment]
+1

**Comment by cartisan** [comment]
In case you want your comments to be aligned at the indentation level of left-most part to be commented out:
```python
for i in range(10):
    #if i / 2 == 0:
    #    print "Ciao"
print "finito"
```

You can get the index for indentation by calling 
`let leftAlignIndx = s:LeftMostIndx(a:forceNested, 0, a:firstLine, a:lastLine)` and use this index as last argument for the mentioned call `let theLine = s:AddLeftDelimAligned(s:Left({'space': 1}), theLine, 0)`. This obviously has to happen in the definition of function `function s:CommentLinesToggle`.

**Comment by codemedic** [comment]
Yes please; it will be a great to be able to toggle comments, aligned.

**Comment by tregusti** [comment]
Ok, can someone a little more seasoned with vim take over this plugin and merge the PRs to the new fork? @scrooloose is obviously not interested in it anymore looking at the lack of response to any PR or issue filed here.

Please?

I don't want to create yet another fork as 257 ppl already did just to have to get some simple PR in.

**Comment by alerque** [comment]
I've been added as a maintainer to this repository, and PR #24 which adds this feature has been merged. Happy commenting everybody.
