### ISSUE TITLE
Commenting .ss (lisp scheme) properly

### ISSUE THREAD

**Issue by gejr** [scrooloose/nerdcommenter#61]
Not sure where to put this question. I'm trying to get nerdcommenter to properly comment a scheme file.
When i hit ,c<space> it comments with the C-style /* */ it should be a leading ; for single-line comments.
I assume this C-style is the default for unknown filetypes?

I've tried modifying the script myself and adding something like:

```
elseif a:filetype ==? "ss"
     call s:MapDelimiters(';', '')

```
This seems to work for other languages. Have I missed something? Is "ss" interpreted in some weird way? I know that I'm editing the right file, because if I change the comment-style of e.g. C-files, the changes appear appropriately in C comments.

Ideally I suppose it should be like this:

```
elseif a:filetype ==? "lisp <OR> ss"
      call s:MapDelimitersWithAlternative(';','', '#|', '|#')
```

Can I get some directions? Feel free to delete this issue, as it's probably just me being retarded, and not really a bug or feature request :-)

Anyways, I'm currently on: 
vim 7.0
NERD_commenter version 2.2.2

**Comment by alerque** [comment]
I've added support for `*.ss` files, so you should be able to ditch the custom variables and just update your plugin @gejr. Rocket support has also been added so the same goes for you @Gonzih. Happy commenting everybody!

**Comment by Gonzih** [comment]
Thanks a lot!
