### ISSUE TITLE
Is there a way of specifying the key starting the mappings

### ISSUE THREAD

**Issue by skeept** [scrooloose/nerdcommenter#80]
Hi I am still using an older version of this script, and in that version all the mappings start with a comma ",".
I see that in the latest version the letter starting the mappings is specified by leader. 
In my case leader is "\" and I would like to keep it that way, but I am used to the mappings provided by this plugin so I would like to know if there is a simple way of customizing it (without having to define all the mappings in my vimrc)

Thanks!

**Comment by rosshadden** [comment]
He mentioned he wants to keep his leader `\`.  According to the docs there does not seem to be a way to customize a key/sequence in place of `<leader>`.  Nor does there appear to be a way to disable the plugin from making any mappings so that we can map them ourselves.  Is this true?  Is there a plan to support this in the future?

Thanks!

**Comment by smichaud** [comment]
I agree, I would really like to be able to change the default mapping. In fact I would like to disable them and only create a new mapping for the comment toggling feature.

**Comment by al3xandru** [comment]
👍 for being able to disable all default mappings and defining your own. (I'm currently trying to figure out how to solve a conflict between 2 plugins)

**Comment by alerque** [comment]
The existing  mappings may be individually overridden with `NERDComMappings`, see the documentation in `:help nerdcommenter` for more information. All of the functions can be mapped to functions using `<plug>NERDCommenterComment` (or whatever function you are trying to map).

You may disable all the default mappings using `let g:NERDCreateDefaultMappings = 0`.

The leader can be changed in your vim settings.

I don't think there is anything actually left to do here, but if I'm missing something please comment and let me know.
