### ISSUE TITLE
Is there any way to toggle a commented block without selecting all the lines?

### ISSUE THREAD

**Issue by Ziiweb** [scrooloose/nerdcommenter#85]
Hi,

is there any way to toggle a commented block without selecting all the lines? I mean, being the cursor in a commented line with other commented lines up and down,  I would like to toggle all those commented lines without selecting the lines before.

Javi

**Comment by ggVGc** [comment]
I second this. I was just now wanting "Uncomment current block". I.e place the cursor inside the comment block(only makes sense for compact comments), and uncomment it, without having to visually select the whole thing first.

**Comment by alerque** [comment]
This is already possible. The trick is if the block comment format is the alternate delimiter for your language you need to make it the primary. Use `<leader>ca` to toggle the primary/alternate delimiters, then uncommenting should work for the block under the cursor without having to select the whole thing.
