### ISSUE TITLE
SQL comments for MySQL

### ISSUE THREAD

**Issue by bogdan** [scrooloose/nerdcommenter#92]
MySQL require a space after double dash in order to create line comments.

This is not a valid comment:

``` sql
SELECT `coupons`.* FROM `coupons`  
WHERE `coupons`.coupon_list_id = 55 AND coupons.expires_at IS NULL      
AND `coupons`.coupon_list_id = 55   
--ORDER BY expires_at 
LIMIT 1;
```

And here is valid one:

``` sql
SELECT `coupons`.* FROM `coupons`  
WHERE `coupons`.coupon_list_id = 55 AND coupons.expires_at IS NULL      
AND `coupons`.coupon_list_id = 55   
-- ORDER BY expires_at 
LIMIT 1;
```

Can you please modify SQL commenter to always include that space?

**Comment by alerque** [comment]
This appears to have been fixed already. Let me know if it isn't working for you in the current version.

**Comment by bogdan** [comment]
Yes, it works
