### ISSUE TITLE
would be nice if there was a space

### ISSUE THREAD

**Issue by chovy** [scrooloose/nerdcommenter#94]
highlight text and type \cs does what I want, only it would be nice if there was a space after the *

```
 /*
  *comment
  *comment
  */
```

becomes

```
 /*
  * comment
  * comment
  */
```

Also, I see a leading /** a lot, don't know what thats about, but it looks like common practice

```
 /**
  * comment
  * comment
  */
```

**Comment by alerque** [comment]
There is a setting for this that you can change to suite your fancy. See the documentation (`:help nerd`) for more info, but the short version is you can add `let g:NERDSpaceDelims = 1` to your rc file.
