### ISSUE TITLE
NERD_<filetype>_alt_style ignored

### ISSUE THREAD

**Issue by johntyree** [scrooloose/nerdcommenter#99]
It appears that `g:NERD_c_alt_style`, for example, gets ignored. When I set this in `.vimrc` and then comment something, I still get old style `/* */` comments. If I do `,ca` it will switch as expected.

Am I doing something wrong here?

Also `:echo g:NERD_c_alt_style` shows `1`.

**Comment by benjamincharity** [comment]
+1

**Comment by johntyree** [comment]
Srsly.

**Comment by acgtyrant** [comment]
This is a duplicate of Issue #33, close it please.

**Comment by johntyree** [comment]
Closed in favor of #33
